spring:
  application:
    name: quoting-vk-bot

server:
  base-path: /vk_bot

vk:
  confirmation:
    address:
      code: ENC(E1JMv7KUdwLMzN8jwDst9iH3b78DeVJFQkLGFmIlg9I=)
  group:
    id: 226335516

jasypt:
  encryptor:
    password: ${VK_JASYPT_SECRET}
    algorithm: PBEWithMD5AndDES